---

# nginx
webserver_nginx_conf_sites_dir: /etc/nginx/sites
# following var is good for AWS App ELB healthcheck
# webserver_nginx_default_server_extra_parameters: |-
#   return 403;
webserver_nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
